name: Actualizar archivo XML diariamente

on:
  schedule:
    # Se ejecuta todos los días a las 05:00 UTC
    - cron: '0 5 * * *'
  workflow_dispatch: # Permite ejecutar el proceso manualmente desde GitHub

jobs:
  actualizar-xml:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Garantiza permisos para subir cambios al repositorio

    steps:
      - name: Copiar repositorio
        uses: actions/checkout@v4

      - name: Descargar XML de Open-EPG
        run: |
          curl -sSL -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" "https://www.open-epg.com/files/peru2.xml" -o peru2.xml

      - name: Verificar que el archivo no esté vacío
        run: |
          if [ ! -s peru2.xml ]; then
            echo "El archivo XML descargado está vacío. Cancelando para no sobrescribir datos válidos."
            exit 1
          fi

      - name: Guardar y subir cambios
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add peru2.xml
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update peru2.xml [$(date +'%Y-%m-%d')]" && git push)
